// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATqa4fdwUPUpIm3hRytN1Idz1yZzR_tuk',
    appId: '1:951577124432:web:820e07b089495161e83b55',
    messagingSenderId: '951577124432',
    projectId: 'projectmad-6e072',
    authDomain: 'projectmad-6e072.firebaseapp.com',
    storageBucket: 'projectmad-6e072.firebasestorage.app',
    measurementId: 'G-1V0T3G8H1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy65AOmFxiBdP8Heda0ljrgsQdNANK2Tk',
    appId: '1:951577124432:android:6d9b0d2c63d9e7f4e83b55',
    messagingSenderId: '951577124432',
    projectId: 'projectmad-6e072',
    storageBucket: 'projectmad-6e072.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBNZ6w4c9ff1in98LGbrfEnl5R5xItbWc',
    appId: '1:951577124432:ios:ca5218c15823c88ce83b55',
    messagingSenderId: '951577124432',
    projectId: 'projectmad-6e072',
    storageBucket: 'projectmad-6e072.firebasestorage.app',
    iosBundleId: 'com.example.projectmad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBNZ6w4c9ff1in98LGbrfEnl5R5xItbWc',
    appId: '1:951577124432:ios:ca5218c15823c88ce83b55',
    messagingSenderId: '951577124432',
    projectId: 'projectmad-6e072',
    storageBucket: 'projectmad-6e072.firebasestorage.app',
    iosBundleId: 'com.example.projectmad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATqa4fdwUPUpIm3hRytN1Idz1yZzR_tuk',
    appId: '1:951577124432:web:029e6a9c4749cec3e83b55',
    messagingSenderId: '951577124432',
    projectId: 'projectmad-6e072',
    authDomain: 'projectmad-6e072.firebaseapp.com',
    storageBucket: 'projectmad-6e072.firebasestorage.app',
    measurementId: 'G-V9EBZ225MD',
  );
}
